# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "ekstg-terraform-state"
    encrypt = true
    key     = "qa2/ap-south-1/service_account/terraform1.tfstate"
    region  = "us-east-2"
  }
}
